# Generated by Django 5.2 on 2025-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('supplier', 'Supplier')], max_length=10, null=True),
        ),
    ]
