# Generated by Django 4.2 on 2025-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
