# Generated by Django 4.2 on 2025-05-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_supplier_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('measure_unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Litre')], db_index=True, max_length=10)),
                ('measure_unit_amount', models.PositiveIntegerField(db_index=True)),
                ('measure_state', models.CharField(choices=[('froz', 'Frozen'), ('not froz', 'Not frozen')], db_index=True, max_length=10)),
                ('available_quantity', models.PositiveIntegerField(db_index=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
        ),
    ]
